export type GameFormInput = {
  activePaytableId?: unknown;
  autoGenerateDraws?: unknown;
  availableSpots?: unknown;
  bullseyeEnabled?: unknown;
  defaultCutoffTime?: unknown;
  defaultDrawTime?: unknown;
  drawIdPrefix?: unknown;
  drawIntervalSeconds?: unknown;
  gameType?: unknown;
  mainNumbersCount?: unknown;
  mainNumbersMax?: unknown;
  mainNumbersMin?: unknown;
  name?: unknown;
  numberRangeMax?: unknown;
  numberRangeMin?: unknown;
  numbersDrawn?: unknown;
  payoutMultiplier?: unknown;
  recurringFrequency?: unknown;
  scheduleType?: unknown;
  state?: unknown;
  [field: string]: unknown;
};

export type GameRecord = GameFormInput & {
  activePaytableId?: unknown;
  allowedSpotCounts?: unknown;
  autoGenerateDraws?: unknown;
  availableSpots?: unknown;
  drawCount?: unknown;
  drawFrequencyType?: unknown;
  drawIdPrefix?: unknown;
  drawIntervalSeconds?: unknown;
  externalId?: unknown;
  gameFamily?: unknown;
  id?: unknown;
  name?: unknown;
  numberPoolMax?: unknown;
  numberPoolMin?: unknown;
  payoutMultiplier?: unknown;
  requiresPaytable?: unknown;
  state?: unknown;
};

export type DrawingRecord = {
  externalId?: string | number | null;
  gameId?: string | number | null;
  id?: string | number | null;
  [field: string]: unknown;
};

export type GamePayloadResult<TGame extends GameRecord> =
  | {
      ok: true;
      message: "";
      payload: TGame;
    }
  | {
      ok: false;
      message: string;
      payload: null;
    };
