export const IDENTITY_CLASSES = {
  PLATFORM_OPERATOR: "PLATFORM_OPERATOR",
  HIERARCHY_PARTICIPANT: "HIERARCHY_PARTICIPANT",
  PLAYER: "PLAYER",
  SYSTEM_SERVICE: "SYSTEM_SERVICE",
} as const;

export const USER_STATUSES = {
  ACTIVE: "ACTIVE",
  LOCKED: "LOCKED",
  DISABLED: "DISABLED",
  PENDING_ACTIVATION: "PENDING_ACTIVATION",
} as const;

export const AUTHENTICATION_EVENT_TYPES = {
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED",
  LOGOUT: "LOGOUT",
  PASSWORD_CHANGED: "PASSWORD_CHANGED",
  PASSWORD_RESET_REQUESTED: "PASSWORD_RESET_REQUESTED",
  PASSWORD_RESET_COMPLETED: "PASSWORD_RESET_COMPLETED",
  MFA_ENABLED: "MFA_ENABLED",
  MFA_DISABLED: "MFA_DISABLED",
  SESSION_REVOKED: "SESSION_REVOKED",
  BREAK_GLASS_LOGIN: "BREAK_GLASS_LOGIN",
} as const;

export const MFA_STATUSES = {
  DISABLED: "DISABLED",
  OPTIONAL: "OPTIONAL",
  REQUIRED: "REQUIRED",
  PENDING_SETUP: "PENDING_SETUP",
  ENABLED: "ENABLED",
} as const;

export const SESSION_STATUSES = {
  ACTIVE: "ACTIVE",
  REVOKED: "REVOKED",
  EXPIRED: "EXPIRED",
} as const;

export const BREAK_GLASS_STATUSES = {
  ACTIVE: "ACTIVE",
  USED: "USED",
  DISABLED: "DISABLED",
} as const;

export const DEFAULT_PLATFORM_GROUP_NAMES = [
  "Super Admin",
  "Operations Admin",
  "Settlement Admin",
  "Risk Admin",
  "Compliance Admin",
  "Support Admin",
] as const;
